Issue 72 services groups dao
java-practice-spb-2020/epam-ifmo-java-practice-2020-1 pull request #90
Opened 2020-02-26 10:44 UTC by Arahaon

На текущий момент имеет 4 ошибки, которые исправятся при появлении Service от HacksDev и Esclide

2020-02-26 22:12 UTC, DmitryPuhovsky commented on src/test/java/com/ifmo/epampractice/dao/GroupsDAOTest.java
>          Assert.assertEquals(expectedGroup2, listGroups.get(6));
Здесь нужно expectedGroup1 и  2 сравнивать с realGroup1 и 2, а не с группами взятыми из списка.

2020-02-26 22:13 UTC, DmitryPuhovsky commented
Нужно сделать так, что Трэвис выдавал положительный результат проверки.

2020-02-27 12:57 UTC, Wedds requested changes

2020-02-27 12:57 UTC, Wedds commented on src/main/java/com/ifmo/epampractice/service/GroupsService.java
> +            throw new IllegalArgumentException("No group with such id has been found");
В сообщении хорошо сразу указывать id:
 "No group with id " + id + " has been found"

2020-02-27 12:57 UTC, Wedds commented on src/main/java/com/ifmo/epampractice/service/SubjectsService.java
> +        if (SUBJECTS_DAO.getById((id)).isPresent()) {
Можно упростить:
```
return SUBJECTS_DAO.getById((id)).isPresent()
```

2020-02-27 12:57 UTC, Wedds commented on src/main/java/com/ifmo/epampractice/service/GroupsService.java
> +        for (int i = 0; i < name.length(); i++) {
Эти сложные проверки с циклом можно заменить на 2 простые, если воспользоваться регулярными выраженями:
```
        if (name.length() > MAX_LENGTH) {
            System.err.println("Wrong Name parameter: length more than 25");
            throw new IllegalArgumentException("Wrong name parameter: length more than 25");
        }
        if (!name.matches("[\\w-]+")) {
            System.err.println("Wrong Name parameter: unsupported chars have been found");
            throw new IllegalArgumentException("Wrong name parameter: unsupported chars have been found");
        }
```

2020-02-27 15:19 UTC, merged